# Generated by Django 4.2.7 on 2023-11-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام و نام خانوادکی')),
                ('email', models.EmailField(max_length=254, verbose_name='hdldg')),
                ('phone', models.IntegerField(verbose_name='شماره تلفن')),
                ('number', models.IntegerField(max_length=20, verbose_name='تعداد')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('time', models.TimeField(verbose_name='ساعت')),
            ],
        ),
    ]
