# Generated by Django 4.2.7 on 2023-11-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_reserve_options_alter_reserve_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='number',
            field=models.PositiveIntegerField(verbose_name='تعداد'),
        ),
    ]
