# Generated by Django 4.2.7 on 2023-11-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_reserve_email_alter_reserve_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='phone',
            field=models.IntegerField(verbose_name='شماره تلفن'),
        ),
    ]
