# Generated by Django 4.2.7 on 2023-11-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_reserve_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='time',
            field=models.TimeField(auto_now_add=True, verbose_name='ساعت'),
        ),
    ]
