# Generated by Django 4.2.7 on 2023-11-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name_plural': 'غداها'},
        ),
        migrations.AddField(
            model_name='food',
            name='tye_pood',
            field=models.CharField(choices=[('drinks', 'نوشیدنی ها'), ('lunch', 'ناهار'), ('dinner', 'شام')], default='drinks', max_length=50, verbose_name='نوع غذا'),
        ),
    ]
