# Generated by Django 4.2.7 on 2023-11-27 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_food_options_food_tye_pood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='tye_pood',
            new_name='tye_food',
        ),
    ]
